Simplify helm chart

diff --git a/charts/hdfs-namenode-k8s/templates/namenode-statefulset.yaml b/charts/hdfs-namenode-k8s/templates/namenode-statefulset.yaml
--- a/charts/hdfs-namenode-k8s/templates/namenode-statefulset.yaml
+++ b/charts/hdfs-namenode-k8s/templates/namenode-statefulset.yaml
@@ -7,35 +7,14 @@ metadata:
     app: {{ template "hdfs-k8s.namenode.name" . }}
     chart: {{ template "hdfs-k8s.subchart" . }}
     release: {{ .Release.Name }}
-  annotations:
-    # TODO: Deprecated. Replace tolerate-unready-endpoints with
-    # v1.Service.PublishNotReadyAddresses.
-    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
 spec:
   ports:
   - port: 8020
     name: fs
-  - port: 50070
-    name: http
   clusterIP: None
   selector:
     app: {{ template "hdfs-k8s.namenode.name" . }}
     release: {{ .Release.Name }}
----
-apiVersion: policy/v1beta1
-kind: PodDisruptionBudget
-metadata:
-  name: {{ template "hdfs-k8s.namenode.fullname" . }}
-  labels:
-    app: {{ template "hdfs-k8s.namenode.name" . }}
-    chart: {{ template "hdfs-k8s.subchart" . }}
-    release: {{ .Release.Name }}
-spec:
-  selector:
-    matchLabels:
-      app: {{ template "hdfs-k8s.namenode.name" . }}
-      release: {{ .Release.Name }}
-  minAvailable: 1
 ---
 # Provides namenode helper scripts. Most of them are start scripts
 # that meet different needs.
@@ -51,16 +30,8 @@ metadata:
 data:
   # A bootstrap script which will start namenode daemons after conducting
   # optional metadata initialization steps. The metadata initialization
-  # steps will take place in case the metadata dir is empty,
-  # which will be the case only for the very first run. The specific steps
-  # will differ depending on whether the namenode is active or standby.
-  # We also assume, for the very first run, namenode-0 will be active and
-  # namenode-1 will be standby as StatefulSet will launch namenode-0 first
-  # and zookeeper will determine the sole namenode to be the active one.
-  # For active namenode, the initialization steps will format the metadata,
-  # zookeeper dir and journal node data entries.
-  # For standby namenode, the initialization steps will simply receieve
-  # the first batch of metadata updates from the journal node.
+  # steps will take place in case the metadata dir is empty, which will
+  # be the case only for the very first run.
   format-and-run.sh: |
     #!/usr/bin/env bash
     # Exit on error. Append "|| true" if you expect an error.
@@ -77,27 +48,11 @@ data:
 
     _HDFS_BIN=$HADOOP_PREFIX/bin/hdfs
     _METADATA_DIR=/hadoop/dfs/name/current
-    if [[ "$MY_POD" = "$NAMENODE_POD_0" ]]; then
-      if [[ ! -d $_METADATA_DIR ]]; then
-          $_HDFS_BIN --config $HADOOP_CONF_DIR namenode -format  \
-              -nonInteractive hdfs-k8s ||
-              (rm -rf $_METADATA_DIR; exit 1)
-      fi
-      _ZKFC_FORMATTED=/hadoop/dfs/name/current/.hdfs-k8s-zkfc-formatted
-      if [[ ! -f $_ZKFC_FORMATTED ]]; then
-        _OUT=$($_HDFS_BIN --config $HADOOP_CONF_DIR zkfc -formatZK -nonInteractive 2>&1)
-        # zkfc masks fatal exceptions and returns exit code 0
-        (echo $_OUT | grep -q "FATAL") && exit 1
-        touch $_ZKFC_FORMATTED
-      fi
-    elif [[ "$MY_POD" = "$NAMENODE_POD_1" ]]; then
-      if [[ ! -d $_METADATA_DIR ]]; then
-        $_HDFS_BIN --config $HADOOP_CONF_DIR namenode -bootstrapStandby  \
-            -nonInteractive ||  \
+    if [[ ! -d $_METADATA_DIR ]]; then
+        $_HDFS_BIN --config $HADOOP_CONF_DIR namenode -format  \
+            -nonInteractive hdfs-k8s ||
             (rm -rf $_METADATA_DIR; exit 1)
-      fi
     fi
-    $HADOOP_PREFIX/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR start zkfc
     $_HDFS_BIN --config $HADOOP_CONF_DIR namenode
 
   # A start script that will just hang indefinitely. A user can then get
@@ -124,7 +79,8 @@ spec:
       app: {{ template "hdfs-k8s.namenode.name" . }}
       release: {{ .Release.Name }}
   serviceName: {{ template "hdfs-k8s.namenode.fullname" . }}
-  replicas: 2
+  # Create a size-1 set.
+  replicas: 1
   template:
     metadata:
       labels:
@@ -135,36 +91,9 @@ spec:
 {{ toYaml .Values.podAnnotations | indent 8 }}
       {{- end }}
     spec:
-      {{- if .Values.hostNetworkEnabled }}
-      # Use hostNetwork so datanodes connect to namenode without going through an overlay network
-      # like weave. Otherwise, namenode fails to see physical IP address of datanodes.
-      # Disabling this will break data locality as namenode will see pod virtual IPs and fails to
-      # equate them with cluster node physical IPs associated with data nodes.
-      # We currently disable this only for CI on minikube.
-      hostNetwork: true
-      hostPID: true
-      dnsPolicy: ClusterFirstWithHostNet
-      {{- else }}
-      dnsPolicy: ClusterFirst
-      {{- end }}
       {{- if .Values.affinity }}
       affinity:
 {{ toYaml .Values.affinity | indent 8 }}
-      {{- else if .Values.global.defaultAffinityEnabled }}
-      affinity:
-        podAntiAffinity:
-          requiredDuringSchedulingIgnoredDuringExecution:
-            - labelSelector:
-                matchExpressions:
-                  - key: "app"
-                    operator: In
-                    values:
-                      - {{ template "hdfs-k8s.namenode.name" . }}
-                  - key: "release"
-                    operator: In
-                    values:
-                      - {{ .Release.Name }}
-              topologyKey: "kubernetes.io/hostname"
       {{- end }}
       {{- if .Values.nodeSelector }}
       nodeSelector:
@@ -174,43 +103,37 @@ spec:
       tolerations:
 {{ toYaml .Values.tolerations | indent 8 }}
       {{- end }}
+      # Use hostNetwork so datanodes connect to namenode without going through an overlay network
+      # like weave. Otherwise, namenode fails to see physical IP address of datanodes.
+      hostNetwork: true
+      hostPID: true
+      dnsPolicy: ClusterFirstWithHostNet
       containers:
-        # TODO: Support hadoop version as option.
         - name: hdfs-namenode
           image: uhopper/hadoop-namenode:2.7.2
           env:
             - name: HADOOP_CUSTOM_CONF_DIR
               value: /etc/hadoop-custom-conf
-            - name: MULTIHOMED_NETWORK
-              value: "0"
+            - name: CLUSTER_NAME
+              value: hdfs-k8s
             # Used by the start script below.
             - name: MY_POD
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
-            - name: NAMENODE_POD_0
-              value: {{ template "namenode-pod-0" . }}
-            - name: NAMENODE_POD_1
-              value: {{ template "namenode-pod-1" . }}
+          ports:
+          - containerPort: 8020
+            name: fs
           command: ['/bin/sh', '-c']
           # The start script is provided by a config map.
           args:
             - /entrypoint.sh "/nn-scripts/{{ .Values.namenodeStartScript }}"
-          ports:
-          - containerPort: 8020
-            name: fs
-          - containerPort: 50070
-            name: http
           volumeMounts:
             - name: nn-scripts
               mountPath: /nn-scripts
               readOnly: true
-            # Mount a subpath of the volume so that the name subdir would be a
-            # brand new empty dir. This way, we won't get affected by existing
-            # files in the volume top dir.
-            - name: metadatadir
+            - name: hdfs-name
               mountPath: /hadoop/dfs/name
-              subPath: name
             - name: hdfs-config
               mountPath: /etc/hadoop-custom-conf
               readOnly: true
@@ -264,20 +187,15 @@ spec:
         - name: kerberos-keytab-copy
           emptyDir: {}
         {{- end }}
-      {{- if .Values.global.podSecurityContext.enabled }}
-      securityContext:
-        runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
-        fsGroup: {{ .Values.global.podSecurityContext.fsGroup }}
-      {{- end }}
   volumeClaimTemplates:
     - metadata:
-        name: metadatadir
+        name: hdfs-name
       spec:
         accessModes:
-          - {{ .Values.persistence.accessMode | quote }}
+          - {{ .Values.persistence.accessMode }}
         resources:
           requests:
-            storage: {{ .Values.persistence.size | quote }}
+            storage: {{ .Values.persistence.size }}
       {{- if .Values.persistence.storageClass }}
         {{- if (eq "-" .Values.persistence.storageClass) }}
         storageClassName: ""
@@ -285,7 +203,7 @@ spec:
         storageClassName: "{{ .Values.persistence.storageClass }}"
         {{- end }}
       {{- end }}
-      {{- if .Values.persistence.selector }}
+       {{- if .Values.persistence.selector }}
         selector:
 {{ toYaml .Values.persistence.selector | indent 10 }}
-      {{- end }}
+       {{- end }}
